language: objective-c
osx_image: xcode10
cache: 
  cocoapods: true
before_install:
  - gem install cocoapods
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - pod repo update
before_script:
  - carthage bootstrap --platform osx
script:
  - xcodebuild -workspace TySimulator.xcworkspace -scheme TySimulator -sdk macosx ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES test
after_success:
  - bash <(curl -s https://codecov.io/bash) -cF osx
